"""Officially named domestic research units used to bootstrap nationwide scans.

These records are discovery seeds, not final advantage judgements. The domain
research pipeline must still verify current team identity, geography, domain
relevance and advantage evidence before a non-zero total score is published.
"""
from __future__ import annotations

from typing import Any


NATIONWIDE_TEAM_SEEDS: dict[str, list[dict[str, Any]]] = {
    "科学通用底座": [
        {
            "institution": "中国科学院计算技术研究所",
            "team": "高性能计算机研究中心",
            "subdomain": "科学计算与仿真",
            "directions": ["高性能计算", "并行算法", "科学计算"],
            "url": "https://ict.cas.cn/ky/kygk/",
        },
        {
            "institution": "中国科学院计算技术研究所",
            "team": "高通量计算机研究中心",
            "subdomain": "科学计算与仿真",
            "directions": ["高通量计算", "并行算法", "计算系统"],
            "url": "http://ict.cas.cn/jssgk/zzjg/kyxt/",
        },
        {
            "institution": "中国科学院计算技术研究所",
            "team": "网络数据科学与技术重点实验室",
            "subdomain": "科研数据与知识工程",
            "directions": ["数据科学", "知识计算", "机器学习"],
            "url": "https://ict.cas.cn/ky/kygk/",
        },
        {
            "institution": "中国科学院计算机网络信息中心",
            "team": "高性能计算技术与应用发展部",
            "subdomain": "科学计算与仿真",
            "directions": ["E级计算", "科学计算软件", "领域计算"],
            "url": "https://cnic.cas.cn/jgsz/kyywbm/gxnjsjsyyyfzb/",
        },
        {
            "institution": "中国科学院计算机网络信息中心",
            "team": "并行算法与共性技术研发实验室",
            "subdomain": "科学计算与仿真",
            "directions": ["并行算法", "异构计算", "基础软件"],
            "url": "https://cnic.cas.cn/jgsz/kyywbm/gxnjsjsyyyfzb/",
        },
        {
            "institution": "中国科学院计算机网络信息中心",
            "team": "科学计算应用软件实验室",
            "subdomain": "科学计算与仿真",
            "directions": ["科学计算软件", "计算平台", "应用示范"],
            "url": "https://cnic.cas.cn/jgsz/kyywbm/gxnjsjsyyyfzb/",
        },
        {
            "institution": "深圳大学",
            "team": "广东省普及型高性能计算机重点实验室",
            "subdomain": "科学计算与仿真",
            "directions": ["高性能计算", "系统软件", "生物信息计算"],
            "url": "https://nhpcc.szu.edu.cn/sysgk/sysjj.htm",
        },
        {
            "institution": "深圳大学",
            "team": "大数据系统计算技术国家工程实验室",
            "subdomain": "科研数据与知识工程",
            "directions": ["大数据计算", "云计算", "数据分析"],
            "url": "https://nhpcc.szu.edu.cn/sysgk/sysjj.htm",
        },
    ],
    "通用 AI": [
        {
            "institution": "中国科学院自动化研究所",
            "team": "多模态人工智能系统全国重点实验室",
            "subdomain": "基础模型与多模态",
            "directions": ["多模态人工智能", "基础模型", "认知智能"],
            "url": "http://ia.cas.cn/gkjj/yjsjj/",
        },
        {
            "institution": "中国科学院自动化研究所",
            "team": "复杂系统认知与决策国家级重点实验室",
            "subdomain": "推理与智能体",
            "directions": ["复杂系统", "智能决策", "博弈智能"],
            "url": "http://ia.cas.cn/gkjj/yjsjj/",
        },
        {
            "institution": "中国科学院自动化研究所",
            "team": "脑图谱与类脑智能实验室",
            "subdomain": "基础模型与多模态",
            "directions": ["类脑智能", "脑图谱", "机器学习"],
            "url": "http://www.ia.cas.cn/index.html",
        },
        {
            "institution": "中国科学院自动化研究所",
            "team": "紫东太初大模型研究中心",
            "subdomain": "基础模型与多模态",
            "directions": ["大模型", "多模态", "科学基础模型"],
            "url": "http://www.ia.cas.cn/index.html",
        },
        {
            "institution": "清华大学人工智能学院",
            "team": "T-STAR Lab",
            "subdomain": "安全评测与治理",
            "directions": ["机器学习", "大模型安全", "生成式人工智能"],
            "url": "https://collegeai.tsinghua.edu.cn/kxyj/ktzjs.htm",
        },
        {
            "institution": "清华大学人工智能学院",
            "team": "AI Agent课题组",
            "subdomain": "推理与智能体",
            "directions": ["AI Agent", "大模型", "软件工程"],
            "url": "https://collegeai.tsinghua.edu.cn/kxyj/ktzjs.htm",
        },
        {
            "institution": "清华大学人工智能学院",
            "team": "多模态智能课题组",
            "subdomain": "基础模型与多模态",
            "directions": ["多模态大模型", "生成式人工智能"],
            "url": "https://collegeai.tsinghua.edu.cn/kxyj/ktzjs.htm",
        },
        {
            "institution": "上海交通大学",
            "team": "机器智能基础与应用实验室（MIFA Lab）",
            "subdomain": "基础模型与多模态",
            "directions": ["预训练模型", "持续学习", "多模态学习"],
            "url": "https://mifa.sjtu.edu.cn/",
        },
    ],
    "高能物理与量子科技": [
        {
            "institution": "中国科学院高能物理研究所",
            "team": "北京正负电子对撞机国家实验室",
            "subdomain": "高能粒子物理",
            "directions": ["粒子物理", "正负电子对撞", "北京谱仪"],
            "url": "https://ihep.cas.cn/zdsys/",
        },
        {
            "institution": "中国科学院高能物理研究所",
            "team": "粒子天体物理全国重点实验室",
            "subdomain": "高能粒子物理",
            "directions": ["粒子天体物理", "宇宙线", "高能天体"],
            "url": "https://ihep.cas.cn/gk/jj/",
        },
        {
            "institution": "中国科学院高能物理研究所",
            "team": "高能物理前沿研究中心",
            "subdomain": "高能粒子物理",
            "directions": ["高能物理", "粒子物理前沿"],
            "url": "https://ihep.cas.cn/zdsys/",
        },
        {
            "institution": "中国科学院高能物理研究所",
            "team": "实验物理中心",
            "subdomain": "高能粒子物理",
            "directions": ["实验粒子物理", "探测器"],
            "url": "https://ihep.cas.cn/2019/",
        },
        {
            "institution": "中国科学院高能物理研究所",
            "team": "粒子天体物理中心",
            "subdomain": "高能粒子物理",
            "directions": ["宇宙线", "粒子天体物理"],
            "url": "https://ihep.cas.cn/2019/",
        },
        {
            "institution": "中国科学院高能物理研究所",
            "team": "加速器中心",
            "subdomain": "核物理与加速器",
            "directions": ["加速器物理", "加速器技术"],
            "url": "https://ihep.cas.cn/2019/",
        },
        {
            "institution": "中国科学技术大学",
            "team": "量子物理与量子信息研究部",
            "subdomain": "量子通信与精密测量",
            "directions": ["量子通信", "量子计算", "量子精密测量"],
            "url": "https://quantum.ustc.edu.cn/web/",
        },
        {
            "institution": "中国科学技术大学",
            "team": "中国科学院量子信息重点实验室",
            "subdomain": "量子计算与模拟",
            "directions": ["量子计算", "量子网络", "量子模拟"],
            "url": "http://lqcc.ustc.edu.cn/about.html",
        },
    ],
    "化学与材料": [
        {
            "institution": "中国科学院金属研究所",
            "team": "沈阳材料科学国家研究中心",
            "subdomain": "合金与结构材料",
            "directions": ["先进合金", "材料设计"],
            "url": "https://www.imr.ac.cn/",
        },
        {
            "institution": "中国科学院金属研究所",
            "team": "先进炭材料研究部",
            "subdomain": "合金与结构材料",
            "directions": ["先进炭材料", "结构材料"],
            "url": "https://www.imr.ac.cn/",
        },
        {
            "institution": "北京科技大学",
            "team": "新材料技术研究院",
            "subdomain": "材料发现与材料基因组",
            "directions": ["高温合金", "材料加工"],
            "url": "https://www.ustb.edu.cn/",
        },
        {
            "institution": "西北工业大学",
            "team": "凝固技术国家重点实验室",
            "subdomain": "合金与结构材料",
            "directions": ["合金凝固", "航空材料"],
            "url": "https://www.nwpu.edu.cn/",
        },
        {
            "institution": "清华大学",
            "team": "材料基因组工程研究中心",
            "subdomain": "材料发现与材料基因组",
            "directions": ["材料基因组", "计算材料"],
            "url": "https://www.tsinghua.edu.cn/",
        },
        {
            "institution": "上海交通大学",
            "team": "轻合金精密成型国家工程研究中心",
            "subdomain": "合金与结构材料",
            "directions": ["轻合金", "精密成型"],
            "url": "https://www.sjtu.edu.cn/",
        },
        {
            "institution": "哈尔滨工业大学",
            "team": "先进焊接与连接国家重点实验室",
            "subdomain": "合金与结构材料",
            "directions": ["材料连接", "先进制造"],
            "url": "https://www.hit.edu.cn/",
        },
        {
            "institution": "中国科学院物理研究所",
            "team": "先进材料与结构分析实验室",
            "subdomain": "材料发现与材料基因组",
            "directions": ["材料结构", "凝聚态材料"],
            "url": "https://www.iphy.ac.cn/",
        },
    ],
    "生命科学与医学": [
        {
            "institution": "中国科学院生物物理研究所",
            "team": "生物大分子国家重点实验室",
            "subdomain": "蛋白质结构与设计",
            "directions": ["结构生物学", "生物大分子"],
            "url": "https://www.ibp.cas.cn/",
        },
        {
            "institution": "中国科学院上海营养与健康研究所",
            "team": "营养与代谢国家重点实验室",
            "subdomain": "医学影像与临床AI",
            "directions": ["营养代谢", "生命健康"],
            "url": "https://www.sinh.cas.cn/",
        },
        {
            "institution": "中国科学院遗传与发育生物学研究所",
            "team": "植物基因组学国家重点实验室",
            "subdomain": "基因组与单细胞",
            "directions": ["基因组学", "智能育种"],
            "url": "https://www.genetics.ac.cn/",
        },
        {
            "institution": "清华大学",
            "team": "清华大学结构生物学中心",
            "subdomain": "蛋白质结构与设计",
            "directions": ["结构生物学", "蛋白质结构"],
            "url": "https://www.tsinghua.edu.cn/",
        },
        {
            "institution": "北京大学",
            "team": "北京大学生物信息学中心",
            "subdomain": "基因组与单细胞",
            "directions": ["生物信息学", "计算生物学"],
            "url": "https://www.pku.edu.cn/",
        },
        {
            "institution": "中国科学院成都生物研究所",
            "team": "生物资源与生态环境国家重点实验室",
            "subdomain": "合成生物与智能育种",
            "directions": ["生物资源", "生态环境"],
            "url": "https://www.cib.cas.cn/",
        },
        {
            "institution": "中国科学院神经科学研究所",
            "team": "脑与智能技术卓越创新中心",
            "subdomain": "医学影像与临床AI",
            "directions": ["神经科学", "脑科学"],
            "url": "https://www.ion.ac.cn/",
        },
        {
            "institution": "中国科学院分子细胞科学卓越创新中心",
            "team": "分子细胞生物学国家重点实验室",
            "subdomain": "基因组与单细胞",
            "directions": ["分子细胞生物学", "生命科学"],
            "url": "https://www.cscb.cas.cn/",
        },
    ],
    "地球科学": [
        {
            "institution": "中国科学院大气物理研究所",
            "team": "大气环境与极端气象全国重点实验室",
            "subdomain": "天气与气候",
            "directions": ["极端气象", "大气环境", "天气气候"],
            "url": "http://iap.cas.cn/gb/jgsz/kyxt/",
        },
        {
            "institution": "中国科学院大气物理研究所",
            "team": "地球系统数值模拟与应用全国重点实验室",
            "subdomain": "天气与气候",
            "directions": ["地球系统模式", "数值模拟", "气候预测"],
            "url": "https://iap.cas.cn/gb/xwdt/zhxw/202503/t20250304_7545809.html",
        },
        {
            "institution": "中国科学院大气物理研究所",
            "team": "大气和海洋动力学实验室",
            "subdomain": "天气与气候",
            "directions": ["大气动力学", "海洋动力学", "气候模拟"],
            "url": "http://iap.cas.cn/gb/jgsz/kyxt/",
        },
        {
            "institution": "同济大学",
            "team": "海洋地质全国重点实验室",
            "subdomain": "海洋与水文",
            "directions": ["海洋地质", "古海洋", "深海过程"],
            "url": "https://mlab.tongji.edu.cn/10201/list.htm",
        },
        {
            "institution": "武汉大学",
            "team": "测绘遥感信息工程全国重点实验室",
            "subdomain": "遥感与地理空间",
            "directions": ["测绘遥感", "地理空间", "地球智能"],
            "url": "https://liesmars.whu.edu.cn/index.htm",
        },
        {
            "institution": "中国地质大学（武汉）",
            "team": "地质过程与成矿预测全国重点实验室",
            "subdomain": "地质资源与灾害",
            "directions": ["地质过程", "成矿预测", "深地资源"],
            "url": "https://www.cug.edu.cn/kxyj1/gjjkypt.htm",
        },
        {
            "institution": "中国地质大学（武汉）",
            "team": "地质微生物与环境全国重点实验室",
            "subdomain": "地质资源与灾害",
            "directions": ["地质微生物", "环境地质"],
            "url": "https://www.cug.edu.cn/kxyj1/gjjkypt.htm",
        },
        {
            "institution": "中国气象科学研究院",
            "team": "灾害天气科学与技术全国重点实验室",
            "subdomain": "天气与气候",
            "directions": ["灾害天气", "数值预报", "气象防灾"],
            "url": "https://www.cma.gov.cn/ztbd/2025zt/20251121/202511/t20251126_7464786.html",
        },
    ],
}
